# プロジェクト名
name: joppy
# バンドルID
options:
  # バンドルプレフィックス
  bundleIdPrefix: joppy
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja
  
# firebaseの設定
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.21.0
  
# ターゲットごとの設定
targets:
  joppy:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "16.0"
    #採用するfirebaseのサービス
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      
    sources:
      - joppy
      - project.yml
      - .gitignore
      - .swiftlint.yml
      - .swift-version
      
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: chanchrons
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    info:
      path: joppy/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]

  joppyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - joppyTests
    settings:
      base:
        INFO_PLIST_FILE: joppyTests/Info.plist
    dependences:
      - target: joppy
        
  joppyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: joppyUITests
    settings:
      base:
        INFOPLIST_FILE: joppyUITests/Info.plist
    dependencies:
      - target: joppy
